# Generated by Django 2.1.7 on 2019-02-23 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ed_sismos', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VolcanDefEd',
            new_name='SismoDefEd',
        ),
    ]
