# Generated by Django 2.1.7 on 2019-02-21 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ed_ladera', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VolcanDefEd',
            new_name='LaderaDefEd',
        ),
    ]
