# Generated by Django 2.1.7 on 2019-02-21 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VolcanDefEd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('termino', models.CharField(max_length=30)),
                ('definicion', models.CharField(max_length=300)),
            ],
        ),
    ]
