# Generated by Django 2.1.7 on 2019-02-21 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ed_inundaciones', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VolcanDefEd',
            new_name='InundacionesDefEd',
        ),
    ]
