# Generated by Django 2.1.7 on 2019-02-27 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InundacionesDefRef',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtitulo', models.CharField(max_length=80)),
                ('parrafo', models.CharField(max_length=800)),
            ],
        ),
    ]
