# Generated by Django 2.1.7 on 2019-02-22 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ed_asteroides', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VolcanDefEd',
            new_name='AsteroidesDefEd',
        ),
    ]
